SC_SCROLL_LEFT = 0; //Scroll Left
SC_SCROLL_RIGHT = 1; //Scroll Right
SC_SCROLL_UP = 2; //Scroll Up
SC_SCROLL_DOWN = 3; //Scroll Down

SC_MAP_DRAG_SCROLL = 4; //Map drag scroll

SC_ZOOM_IN = 5; //Zoom In
SC_ZOOM_OUT = 6; //Zoom Out
SC_ZOOM_RESET = 7; //Reset Zoom

SC_CLOSE_MENU = 8; //Close opened menu

SC_DEBUG_WINDOW = 9; //Debug window
SC_DEBUG_REVEALMAP = 10; //Debug Menu Reveal Map
SC_DEBUG_VICTORY = 11; //Debug Menu Victory
SC_DEBUG_DEFEAT = 12; //Debug Menu Defeat
SC_DEBUG_ADDSCOUT = 13; //Debug Menu Add Scout

SC_MENU_BUILD = 14; //Build Menu
SC_MENU_RATIO = 15; //Ratio Menu
SC_MENU_STATS = 16; //Stats Menu
SC_MENU_MENU = 17; //Main Menu

SC_ARMY_HALT = 18; //Halt Command
SC_ARMY_SPLIT = 19; //Split up Command
SC_ARMY_LINK = 20; //Linkup Command
SC_ARMY_FOOD = 21; //Food Command
SC_ARMY_STORM = 22; //Storm Command
SC_ARMY_ADD_LINE = 23; //Formation Increase Line Command
SC_ARMY_DEL_LINE = 24; //Formation Shrink Line Command
SC_ARMY_ROTATE_CW = 25; //Turn Right Command
SC_ARMY_ROTATE_CCW = 26; //Turn Left Command

SC_SPEEDUP_1 = 27; //Speed up 1
SC_SPEEDUP_2 = 28; //Speed up 2
SC_SPEEDUP_3 = 29; //Speed up 3
SC_SPEEDUP_4 = 30; //Speed up 4

SC_BEACON = 31; //Beacon
SC_PAUSE = 32; //Pause
SC_SHOW_TEAMS = 33; //Show teams in MP

SC_CENTER_ALERT = 34; //Center to alert
SC_DELETE_MSG = 35; //Delete message
SC_CHAT = 36; //Show the chat

SC_NEXT_BLD_UNIT_SAME_TYPE = 37; //Select next building/unit with same type
SC_PLAYER_COLOR_MODE = 38; //Switch player color mode

SC_PLAN_ROAD = 39; //Plan road
SC_PLAN_FIELD = 40; //Plan field
SC_PLAN_WINE = 41; //Plan wine
SC_ERASE_PLAN = 42; //Erase plan

SC_SELECT_1 = 43; //Select 1
SC_SELECT_2 = 44; //Select 2
SC_SELECT_3 = 45; //Select 3
SC_SELECT_4 = 46; //Select 4
SC_SELECT_5 = 47; //Select 5
SC_SELECT_6 = 48; //Select 6
SC_SELECT_7 = 49; //Select 7
SC_SELECT_8 = 50; //Select 8
SC_SELECT_9 = 51; //Select 9
SC_SELECT_10 = 52; //Select 10
SC_SELECT_11 = 53; //Select 11
SC_SELECT_12 = 54; //Select 12
SC_SELECT_13 = 55; //Select 13
SC_SELECT_14 = 56; //Select 14
SC_SELECT_15 = 57; //Select 15
SC_SELECT_16 = 58; //Select 16
SC_SELECT_17 = 59; //Select 17
SC_SELECT_18 = 60; //Select 18
SC_SELECT_19 = 61; //Select 19
SC_SELECT_20 = 62; //Select 20

SC_SPECPANEL_SELECT_DROPBOX = 63; //Select dropbox on spectator panel
SC_SPECTATE_PLAYER_1 = 64; //Spectate player 1
SC_SPECTATE_PLAYER_2 = 65; //Spectate player 2
SC_SPECTATE_PLAYER_3 = 66; //Spectate player 3
SC_SPECTATE_PLAYER_4 = 67; //Spectate player 4
SC_SPECTATE_PLAYER_5 = 68; //Spectate player 5
SC_SPECTATE_PLAYER_6 = 69; //Spectate player 6
SC_SPECTATE_PLAYER_7 = 70; //Spectate player 7
SC_SPECTATE_PLAYER_8 = 71; //Spectate player 8
SC_SPECTATE_PLAYER_9 = 72; //Spectate player 9
SC_SPECTATE_PLAYER_10 = 73; //Spectate player 10
SC_SPECTATE_PLAYER_11 = 74; //Spectate player 11
SC_SPECTATE_PLAYER_12 = 75; //Spectate player 12

SC_MAPEDIT_EXTRA = 76; // MapEdit Extra's menu
SC_MAPEDIT_TERRAIN = 77; // MapEdit Terrain Editing
SC_MAPEDIT_VILLAGE = 78; // MapEdit Village Planning
SC_MAPEDIT_VISUAL = 79; // MapEdit Visual Scripts
SC_MAPEDIT_GLOBAL = 80; // MapEdit Global Scripting
SC_MAPEDIT_MAIN_MANU = 81; // MapEdit Main Menu
SC_MAPEDIT_SUB_MENU_1 = 82; // MapEdit Sub-menu 1
SC_MAPEDIT_SUB_MENU_2 = 83; // MapEdit Sub-menu 2
SC_MAPEDIT_SUB_MENU_3 = 84; // MapEdit Sub-menu 3
SC_MAPEDIT_SUB_MENU_4 = 85; // MapEdit Sub-menu 4
SC_MAPEDIT_SUB_MENU_5 = 86; // MapEdit Sub-menu 5
SC_MAPEDIT_SUB_MENU_6 = 87; // MapEdit Sub-menu 6
SC_MAPEDIT_SUB_MENU_ACTION_1 = 88; // MapEdit Sub-menu Action 1
SC_MAPEDIT_SUB_MENU_ACTION_2 = 89; // MapEdit Sub-menu Action 2
SC_MAPEDIT_SUB_MENU_ACTION_3 = 90; // MapEdit Sub-menu Action 3
SC_MAPEDIT_SUB_MENU_ACTION_4 = 91; // MapEdit Sub-menu Action 4
SC_MAPEDIT_SUB_MENU_ACTION_5 = 92; // MapEdit Sub-menu Action 5
SC_MAPEDIT_SUB_MENU_ACTION_6 = 93; // MapEdit Sub-menu Action 6
SC_MAPEDIT_SUB_MENU_ACTION_7 = 94; // MapEdit Sub-menu Action 6
SC_MAPEDIT_OBJ_PALETTE = 95; // MapEdit Objects palette
SC_MAPEDIT_UNIV_ERASOR = 96; // MapEdit Universal erasor
SC_MAPEDIT_PAINT_BUCKET = 97; // MapEdit Paint bucket

