SC_SCROLL_LEFT = 0; //Scroll Left
SC_SCROLL_RIGHT = 1; //Scroll Right
SC_SCROLL_UP = 2; //Scroll Up
SC_SCROLL_DOWN = 3; //Scroll Down

SC_MAP_DRAG_SCROLL = 4; //Map drag scroll

SC_ZOOM_IN = 5; //Zoom In
SC_ZOOM_OUT = 6; //Zoom Out
SC_ZOOM_RESET = 7; //Reset Zoom

SC_CLOSE_MENU = 8; //Close opened menu

SC_DEBUG_WINDOW = 9; //Debug window
SC_DEBUG_REVEALMAP = 10; //Debug Menu Reveal Map
SC_DEBUG_VICTORY = 11; //Debug Menu Victory
SC_DEBUG_DEFEAT = 12; //Debug Menu Defeat
SC_DEBUG_ADDSCOUT = 13; //Debug Menu Add Scout

SC_MENU_BUILD = 14; //Build Menu
SC_MENU_RATIO = 15; //Ratio Menu
SC_MENU_STATS = 16; //Stats Menu
SC_MENU_MENU = 17; //Main Menu

SC_SPEEDUP_1 = 18; //Speed up 1
SC_SPEEDUP_2 = 19; //Speed up 2
SC_SPEEDUP_3 = 20; //Speed up 3
SC_SPEEDUP_4 = 21; //Speed up 4

SC_BEACON = 22; //Beacon
SC_PAUSE = 23; //Pause
SC_SHOW_TEAMS = 24; //Show teams in MP

SC_CENTER_ALERT = 25; //Center to alert
SC_DELETE_MSG = 26; //Delete message
SC_CHAT = 27; //Show the chat

SC_NEXT_BLD_UNIT_SAME_TYPE = 28; //Select next building/unit with same type
SC_PLAYER_COLOR_MODE = 29; //Switch player color mode

SC_PLAN_ROAD = 30; //Plan road
SC_PLAN_FIELD = 31; //Plan field
SC_PLAN_WINE = 32; //Plan wine
SC_ERASE_PLAN = 33; //Erase plan

SC_SELECT_1 = 34; //Select 1
SC_SELECT_2 = 35; //Select 2
SC_SELECT_3 = 36; //Select 3
SC_SELECT_4 = 37; //Select 4
SC_SELECT_5 = 38; //Select 5
SC_SELECT_6 = 39; //Select 6
SC_SELECT_7 = 40; //Select 7
SC_SELECT_8 = 41; //Select 8
SC_SELECT_9 = 42; //Select 9
SC_SELECT_10 = 43; //Select 10
SC_SELECT_11 = 44; //Select 11
SC_SELECT_12 = 45; //Select 12
SC_SELECT_13 = 46; //Select 13
SC_SELECT_14 = 47; //Select 14
SC_SELECT_15 = 48; //Select 15
SC_SELECT_16 = 49; //Select 16
SC_SELECT_17 = 50; //Select 17
SC_SELECT_18 = 51; //Select 18
SC_SELECT_19 = 52; //Select 19
SC_SELECT_20 = 53; //Select 20

SC_ARMY_HALT = 54; //Halt Command
SC_ARMY_SPLIT = 55; //Split up Command
SC_ARMY_LINK = 56; //Linkup Command
SC_ARMY_FOOD = 57; //Food Command
SC_ARMY_STORM = 58; //Storm Command
SC_ARMY_ADD_LINE = 59; //Formation Increase Line Command
SC_ARMY_DEL_LINE = 60; //Formation Shrink Line Command
SC_ARMY_ROTATE_CW = 61; //Turn Right Command
SC_ARMY_ROTATE_CCW = 62; //Turn Left Command

SC_TRAIN_GOTO_PREV = 63; //Goto previuos unit
SC_TRAIN_EQUIP_UNIT = 64; //Train or Equip unit
SC_TRAIN_GOTO_NEXT = 65; //Goto next unit

SC_SPECPANEL_SELECT_DROPBOX = 66; //Select dropbox on spectator panel
SC_REPLAY_PLAY_NEXT_TICK = 67; //Play next tick in replay
SC_SPECTATE_PLAYER_1 = 68; //Spectate player 1
SC_SPECTATE_PLAYER_2 = 69; //Spectate player 2
SC_SPECTATE_PLAYER_3 = 70; //Spectate player 3
SC_SPECTATE_PLAYER_4 = 71; //Spectate player 4
SC_SPECTATE_PLAYER_5 = 72; //Spectate player 5
SC_SPECTATE_PLAYER_6 = 73; //Spectate player 6
SC_SPECTATE_PLAYER_7 = 74; //Spectate player 7
SC_SPECTATE_PLAYER_8 = 75; //Spectate player 8
SC_SPECTATE_PLAYER_9 = 76; //Spectate player 9
SC_SPECTATE_PLAYER_10 = 77; //Spectate player 10
SC_SPECTATE_PLAYER_11 = 78; //Spectate player 11
SC_SPECTATE_PLAYER_12 = 79; //Spectate player 12

SC_MAPEDIT_EXTRA = 80; // MapEdit Extra's menu
SC_MAPEDIT_TERRAIN = 81; // MapEdit Terrain Editing
SC_MAPEDIT_VILLAGE = 82; // MapEdit Village Planning
SC_MAPEDIT_VISUAL = 83; // MapEdit Visual Scripts
SC_MAPEDIT_GLOBAL = 84; // MapEdit Global Scripting
SC_MAPEDIT_MAIN_MANU = 85; // MapEdit Main Menu
SC_MAPEDIT_SUB_MENU_1 = 86; // MapEdit Sub-menu 1
SC_MAPEDIT_SUB_MENU_2 = 87; // MapEdit Sub-menu 2
SC_MAPEDIT_SUB_MENU_3 = 88; // MapEdit Sub-menu 3
SC_MAPEDIT_SUB_MENU_4 = 89; // MapEdit Sub-menu 4
SC_MAPEDIT_SUB_MENU_5 = 90; // MapEdit Sub-menu 5
SC_MAPEDIT_SUB_MENU_6 = 91; // MapEdit Sub-menu 6
SC_MAPEDIT_SUB_MENU_ACTION_1 = 92; // MapEdit Sub-menu Action 1
SC_MAPEDIT_SUB_MENU_ACTION_2 = 93; // MapEdit Sub-menu Action 2
SC_MAPEDIT_SUB_MENU_ACTION_3 = 94; // MapEdit Sub-menu Action 3
SC_MAPEDIT_SUB_MENU_ACTION_4 = 95; // MapEdit Sub-menu Action 4
SC_MAPEDIT_SUB_MENU_ACTION_5 = 96; // MapEdit Sub-menu Action 5
SC_MAPEDIT_SUB_MENU_ACTION_6 = 97; // MapEdit Sub-menu Action 6
SC_MAPEDIT_SUB_MENU_ACTION_7 = 98; // MapEdit Sub-menu Action 6
SC_MAPEDIT_OBJ_PALETTE = 99; // MapEdit Objects palette
SC_MAPEDIT_TILES_PALETTE = 100; // MapEdit Tiles palette
SC_MAPEDIT_UNIV_ERASOR = 101; // MapEdit Universal erasor
SC_MAPEDIT_PAINT_BUCKET = 102; // MapEdit Paint bucket
SC_MAPEDIT_HISTORY = 103; // MapEdit History
