@SET BDS=C:\Program Files (x86)\Embarcadero\Studio\18.0
@SET BDSCOMMONDIR=C:\Users\Public\Documents\Embarcadero\Studio\18.0
@SET FrameworkDir=C:\Windows\Microsoft.NET\Framework\v3.5
@SET FrameworkVersion=v3.5
@SET FrameworkSDKDir=
@SET KaMOrigDir=E:\games\KnightsAndMerchants_ORIG
@SET KMRPrevVersionDir=E:\games\KaM\KaM Remake
@SET BuildFullDir=E:\KaM_Remake Beta
@SET PATH=%FrameworkDir%;%FrameworkSDKDir%;%BDS%\bin;%BDS%\bin64;%PATH%
@SET kam_version=Beta 8000+
